# Generated by Django 4.2.16 on 2025-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationchannel',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('telegram', 'Telegram'), ('webhook', 'Webhook'), ('email', 'Email'), ('bale', 'Bale')], max_length=32),
        ),
    ]
