# Generated by Django 4.2.16 on 2025-12-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_destinationchannel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwardrule',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='forwardrule',
            name='source_endpoint',
        ),
    ]
