# Generated by Django 4.2.16 on 2025-12-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_forwardrule_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardrule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_rules', to='monitor.project'),
        ),
    ]
