# Generated by Django 4.2.16 on 2025-12-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_forwardrule_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruledestination',
            name='action_config',
        ),
        migrations.RemoveField(
            model_name='ruledestination',
            name='override_text_template',
        ),
    ]
