# Generated by Django 4.2.16 on 2026-01-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_ruledestination_action_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationchannel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='forwardrule',
            name='project',
        ),
        migrations.RemoveField(
            model_name='incomingmessage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='simendpoint',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
