# Generated by Django 4.2.16 on 2026-01-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_remove_destinationchannel_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingmessage',
            name='endpoint',
        ),
        migrations.DeleteModel(
            name='SimEndpoint',
        ),
    ]
