# Generated by Django 4.2.16 on 2026-01-02 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_incomingmessage_endpoint_delete_simendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.TextField(help_text='The original un-processed payload')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('source_tag', models.CharField(blank=True, default='mqtt_gateway', max_length=64)),
            ],
            options={
                'verbose_name': 'Failed Log',
                'verbose_name_plural': 'Failed Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
